### PR TITLE
Fix scaling for input images

### LINKED ISSUE #37: Load image scaling
It looks like images loaded from the photo library are being stretched vertically. It's great looking skinnier, but I think we should try to display the images as close as possible to the original image.

### PR DESCRIPTION
**Pull request by ianstenbit**
Close #37

### CODE REVIEW

**Review by jakecarlson1 — CHANGES_REQUESTED** [review]
Stylized images look good. I think the loaded image should not have it's top and bottom removed so the image doesn't look as stretched.

**Comment by ianstenbit** [comment]
I've updated it to do the best I can to scale images correctly. There are two ways of doing it. With one, you lose a bit of an image. With the other one, you end up with a lower resolution and big black bars to fill the space. I think we should just stick with this option. Later we could make a bigger fix where we switch to holding all the frames at their native resolution instead of the resolution of the style transfer.

**Comment by ianstenbit** [comment]
If we were to implement a .scaleToFit for the UIImage resize function, then this would work better I think.

**Comment by jakecarlson1** [comment]
This looks good. Will accept. Need to replace the water style with mosaic to match the photo.

**Review by jakecarlson1 — APPROVED** [review]

**Pull request merged**
