### PR TITLE
Makes progress bar for video transfer more attractive.

### LINKED ISSUE #42: Better-looking progress bar
The progress bar for video stylization should be more attractive.

### PR DESCRIPTION
**Pull request by ianstenbit**
Also makes style image stay up for duration of video transfer. Close #42 
Do not merge until #56 is merged.

### CODE REVIEW

**Comment by ianstenbit** [comment]
The conflicts should be resolved automatically when #56 is merged.

**Review by jakecarlson1 — CHANGES_REQUESTED** [review]
This looks really good, good job with the resizing view. Two comments.
1) I think the progress view would look better in a darker color (maybe view flipside background like the old style image preview border was?). (NIT: We may eventually want to play around with a progress bar that loads from bottom to top; might look fancy.)
2) When switching between in progress video style transfer, the progress bar sometimes loads half a second after the style image preview. Is there anyway to put 
self.progressView.isHidden = false
in the showStylePreview function so the progressView is loaded right after the preview image? I realize this is a bit tricky with most of the progress view logic in async calls, but I think this should be weeded out now.

**Comment by ianstenbit** [comment]
I've made the changes. A few notes:
1) To merge this PR, I think you will have to merge the 2 previous ones otherwise there will be git conflicts.
2) In order to make this work, I just removed all the UI constraints on the progress view. If you leave constraints in place, then on any UI draw where you don't explicitly set the frame, it gets reset.

**Review by jakecarlson1 — APPROVED** [review]
This looks good and master could use these changes. It's weird that those constraint errors are now required for the app to load.
I still think there is some more styling that we can do to the progress bar, but that can be addressed in a later PR.

**Comment by jakecarlson1** [comment]
The only merge conflict was a spacing (new line) inconsistency.

**Pull request merged**
